# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    tags:
      - "V*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Build
        shell: bash
        run: |
          # Build everything
          dotnet publish ./src/TPHChristmasRPC.csproj -c Release -r osx-x64 -p:PublishReadyToRun=true --self-contained true /p:PublishSingleFile=true -o "App-OSX"
          tar czvf "App-OSX.tar.gz" "App-OSX"
          rm -r App-OSX
          dotnet publish ./src/TPHChristmasRPC.csproj -c Release -r linux-x64 -p:PublishReadyToRun=true --self-contained true /p:PublishSingleFile=true -o "App-Linux"
          tar czvf "App-Linux.tar.gz" "App-Linux"
          rm -r App-Linux
          dotnet publish ./src/TPHChristmasRPC.csproj -c Release -r linux-arm64 -p:PublishReadyToRun=true --self-contained true /p:PublishSingleFile=true -o "App-Arm64"
          tar czvf "App-Arm64.tar.gz" "App-Arm64"
          rm -r App-Arm64
          dotnet publish ./src/TPHChristmasRPC.csproj -c Release -r win-x64 -p:PublishReadyToRun=true --self-contained true /p:PublishSingleFile=true -o "App-Win-x64"
          7z a -tzip "App-Win-x64.zip" "./App-Win-x64/*"
          rm -r App-Win-x64
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
